# This file configures sonar-cloud for CI-based analysis

sonar.projectName=resin-release-tool
sonar.projectKey=mobilityhouse_resin-release-tool
sonar.host.url=https://sonarcloud.io
sonar.organization=mobilityhouse-2022-sw-quality-booster

sonar.sources=.

## For PR decoration 
sonar.pullrequest.provider=GitHub
sonar.pullrequest.github.repository=mobilityhouse/resin-release-tool

sonar.sca.enabled=true
