name: "Setup Build Environment"
description: "Install everything needed to build"

runs:
  using: "composite"
  steps:
  - name: Upgrade pip and install poetry
    shell: bash
    run: |
      pip install pip==22.1.2 
      pip install --user "poetry==1.1.13"
