version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: 
          command: |
            sudo pip install poetry
            poetry build 

  publish:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install poetry
            poetry publish --build -u ${PYPI_PUBLIC_USERNAME} -p ${PYPI_PUBLIC_PASSWORD}


workflows:
  version: 2
  default:
    jobs:
      - build:
          context: tmh
          filters:
            tags:
              only: /.*/
      - publish:
          context: tmh
          requires:
            - build
          filters:
            tags:
              only:
                - /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
